-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PORTFOLIO MODULO 4 CJ
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PORTFOLIO MODULO 4 CJ
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PORTFOLIO MODULO 4 CJ` DEFAULT CHARACTER SET utf8 ;
USE `PORTFOLIO MODULO 4 CJ` ;

-- -----------------------------------------------------
-- Table `PORTFOLIO MODULO 4 CJ`.`TIPO de EXPERIENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PORTFOLIO MODULO 4 CJ`.`TIPO de EXPERIENCIA` (
  `idTIPO de EXPERIENCIA` INT NOT NULL,
  `tipoExperiencia` VARCHAR(45) NULL,
  PRIMARY KEY (`idTIPO de EXPERIENCIA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PORTFOLIO MODULO 4 CJ`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PORTFOLIO MODULO 4 CJ`.`PERSONA` (
  `idPERSONA` INT NOT NULL,
  `nombrePERSONA` VARCHAR(45) NOT NULL,
  `apellidoPERSONA` VARCHAR(45) NOT NULL,
  `emailPersona` VARCHAR(45) NOT NULL,
  `telefonoPersona` VARCHAR(15) NULL,
  `domicilioPersona` VARCHAR(45) NULL,
  `urlFotoPersona` VARCHAR(45) NULL,
  `sobrePersona` VARCHAR(200) NULL,
  PRIMARY KEY (`idPERSONA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PORTFOLIO MODULO 4 CJ`.` EXPERIENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PORTFOLIO MODULO 4 CJ`.` EXPERIENCIA` (
  `idExperiencia` INT NOT NULL,
  `tFechaInicioExp` DATETIME NOT NULL,
  `fechaFinExp` DATETIME NOT NULL,
  `estáHoyExpe` TINYINT NULL,
  `nombreExper` VARCHAR(18) NULL,
  `telefonoExpe` VARCHAR(200) NULL,
  `domicilioExp` DATETIME NULL,
  `emailExperiencia` VARCHAR(45) NOT NULL,
  `TIPO de EXPERIENCIA_idTIPO de EXPERIENCIA` INT NOT NULL,
  `PERSONA_idPERSONA` INT NOT NULL,
  PRIMARY KEY (`idExperiencia`, `TIPO de EXPERIENCIA_idTIPO de EXPERIENCIA`, `PERSONA_idPERSONA`),
  INDEX `fk_ EXPERIENCIA_TIPO de EXPERIENCIA_idx` (`TIPO de EXPERIENCIA_idTIPO de EXPERIENCIA` ASC) VISIBLE,
  INDEX `fk_ EXPERIENCIA_PERSONA1_idx` (`PERSONA_idPERSONA` ASC) VISIBLE,
  CONSTRAINT `fk_ EXPERIENCIA_TIPO de EXPERIENCIA`
    FOREIGN KEY (`TIPO de EXPERIENCIA_idTIPO de EXPERIENCIA`)
    REFERENCES `PORTFOLIO MODULO 4 CJ`.`TIPO de EXPERIENCIA` (`idTIPO de EXPERIENCIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ EXPERIENCIA_PERSONA1`
    FOREIGN KEY (`PERSONA_idPERSONA`)
    REFERENCES `PORTFOLIO MODULO 4 CJ`.`PERSONA` (`idPERSONA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PORTFOLIO MODULO 4 CJ`.`TIPO de EDUCACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PORTFOLIO MODULO 4 CJ`.`TIPO de EDUCACION` (
  `idTIPO de EDUCACION` INT NOT NULL,
  `tipoEDUCACIONcol` TINYINT NOT NULL,
  `nivelEDUCACION` VARCHAR(45) NULL,
  PRIMARY KEY (`idTIPO de EDUCACION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PORTFOLIO MODULO 4 CJ`.`EDUCACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PORTFOLIO MODULO 4 CJ`.`EDUCACION` (
  `idEDUCACION` INT NOT NULL,
  `nombreEDUCACION` VARCHAR(45) NOT NULL,
  `lugarEDUCACION` VARCHAR(45) NOT NULL,
  `fechaINIC-EDUCACION` DATETIME NULL,
  `fechaFIN-EDUCACION` DATETIME NULL,
  `tituloEDUCACION` VARCHAR(45) NULL,
  `PERSONA_idPERSONA` INT NOT NULL,
  `TIPO de EDUCACION_idTIPO de EDUCACION` INT NOT NULL,
  PRIMARY KEY (`idEDUCACION`, `PERSONA_idPERSONA`, `TIPO de EDUCACION_idTIPO de EDUCACION`),
  INDEX `fk_EDUCACION_PERSONA1_idx` (`PERSONA_idPERSONA` ASC) VISIBLE,
  INDEX `fk_EDUCACION_TIPO de EDUCACION1_idx` (`TIPO de EDUCACION_idTIPO de EDUCACION` ASC) VISIBLE,
  CONSTRAINT `fk_EDUCACION_PERSONA1`
    FOREIGN KEY (`PERSONA_idPERSONA`)
    REFERENCES `PORTFOLIO MODULO 4 CJ`.`PERSONA` (`idPERSONA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EDUCACION_TIPO de EDUCACION1`
    FOREIGN KEY (`TIPO de EDUCACION_idTIPO de EDUCACION`)
    REFERENCES `PORTFOLIO MODULO 4 CJ`.`TIPO de EDUCACION` (`idTIPO de EDUCACION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PORTFOLIO MODULO 4 CJ`.`HABILIDADES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PORTFOLIO MODULO 4 CJ`.`HABILIDADES` (
  `idHABILIDADES` INT NOT NULL,
  `descripcionHABILIDADES` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHABILIDADES`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PORTFOLIO MODULO 4 CJ`.`DETALLE HABILIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PORTFOLIO MODULO 4 CJ`.`DETALLE HABILIDAD` (
  `idDETALLE HABILIDAD` INT NOT NULL,
  `tipoHABILIDAD` VARCHAR(45) NULL,
  `PERSONA_idPERSONA` INT NOT NULL,
  PRIMARY KEY (`idDETALLE HABILIDAD`),
  INDEX `fk_DETALLE HABILIDAD_PERSONA1_idx` (`PERSONA_idPERSONA` ASC) VISIBLE,
  CONSTRAINT `fk_DETALLE HABILIDAD_PERSONA1`
    FOREIGN KEY (`PERSONA_idPERSONA`)
    REFERENCES `PORTFOLIO MODULO 4 CJ`.`PERSONA` (`idPERSONA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PORTFOLIO MODULO 4 CJ`.`HABILIDADES_has_DETALLE HABILIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PORTFOLIO MODULO 4 CJ`.`HABILIDADES_has_DETALLE HABILIDAD` (
  `HABILIDADES_idHABILIDADES` INT NOT NULL,
  `DETALLE HABILIDAD_idDETALLE HABILIDAD` INT NOT NULL,
  PRIMARY KEY (`HABILIDADES_idHABILIDADES`, `DETALLE HABILIDAD_idDETALLE HABILIDAD`),
  INDEX `fk_HABILIDADES_has_DETALLE HABILIDAD_DETALLE HABILIDAD1_idx` (`DETALLE HABILIDAD_idDETALLE HABILIDAD` ASC) VISIBLE,
  INDEX `fk_HABILIDADES_has_DETALLE HABILIDAD_HABILIDADES1_idx` (`HABILIDADES_idHABILIDADES` ASC) VISIBLE,
  CONSTRAINT `fk_HABILIDADES_has_DETALLE HABILIDAD_HABILIDADES1`
    FOREIGN KEY (`HABILIDADES_idHABILIDADES`)
    REFERENCES `PORTFOLIO MODULO 4 CJ`.`HABILIDADES` (`idHABILIDADES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HABILIDADES_has_DETALLE HABILIDAD_DETALLE HABILIDAD1`
    FOREIGN KEY (`DETALLE HABILIDAD_idDETALLE HABILIDAD`)
    REFERENCES `PORTFOLIO MODULO 4 CJ`.`DETALLE HABILIDAD` (`idDETALLE HABILIDAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PORTFOLIO MODULO 4 CJ`.`PROYECTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PORTFOLIO MODULO 4 CJ`.`PROYECTO` (
  `idPROYECTO` INT NOT NULL,
  `descripcionPROYECTO` VARCHAR(45) NOT NULL,
  `url-PROYECTO` VARCHAR(45) NOT NULL,
  `lugarPROYECTO` VARCHAR(45) NOT NULL,
  `tiempo-PROYECTO` VARCHAR(45) NOT NULL,
  `PERSONA_idPERSONA` INT NOT NULL,
  PRIMARY KEY (`idPROYECTO`, `PERSONA_idPERSONA`),
  INDEX `fk_PROYECTO_PERSONA1_idx` (`PERSONA_idPERSONA` ASC) VISIBLE,
  CONSTRAINT `fk_PROYECTO_PERSONA1`
    FOREIGN KEY (`PERSONA_idPERSONA`)
    REFERENCES `PORTFOLIO MODULO 4 CJ`.`PERSONA` (`idPERSONA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PORTFOLIO MODULO 4 CJ`.`TIPO de PROYECTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PORTFOLIO MODULO 4 CJ`.`TIPO de PROYECTO` (
  `idTIPO de PROYECTO` INT NOT NULL,
  `TIPO de PROYECTOcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idTIPO de PROYECTO`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
